package com.epam.command;

public enum CommandName {
    SIGN_IN,
    SIGN_UP,
    INDEX,
    WRONG_REQUEST,
    MEDICAMENT,
    MEDICAMENTS,
    ADD_MEDICAMENT,
    MEDICAMENTS_BY_PRODUCER,
    MEDICAMENTS_BY_NAME,
    MEDICAMENTS_ASC_SORTED_BY_PRICE,
    MEDICAMENTS_DESC_SORTED_BY_PRICE,
    EDIT_MEDICAMENT,
    SIGN_OUT,
    NEW_PRESCRIPTION,
    ADD_PRESCRIPTION,
    ADD_USER,
    GET_USERS,
    GET_MEDICAMENTS,
    GET_MY_PRESCRIPTIONS,
    GET_MY_ORDERS,
    GET_MY_REQUESTS,
    ADD_REQUEST,
    PAY,
    ADD_TO_CART, GET_DOSAGES_BY_MEDICAMENT_ID,
    GET_MY_CART, GET_AND_EDIT_MEDICAMENT
}
